### ISSUE TITLE
Scoreboard optimization

### ISSUE THREAD

**Issue by wingzero54** [CivMC/Finale#1]

**Comment by Maxopoly** [comment]
More details please, what kind of performance issues (caused by what?) were the issue?

**Comment by wingzero54** [comment]
No specific performance issue, just that the Scoreboard HUD is consistently 1% of server performance which isn't huge, but we should take any performance improvements where we can get them. And it strikes me as relatively high usage for what it is. 

Timings for reference: https://timings.aikar.co/?id=f2937ef970784b3a833a7dd7c75075ef

**Comment by Diet-Cola** [comment]
Do we consider this fixed from #18 ?

**Comment by awoo-civ** [comment]
@Diet-Cola Shouldn't, just changing the delay is a hotfix, not a real solution. Five seconds of delay is a lot, not the best experience for players and will still take up way more server compute than necessary.

From previous discussion in Discord:
> awoo: Re: Scoreboard lag. This gets run every 5 ticks: https://github.com/CivMC/Finale/blob/master/paper/src/main/java/com/github/maxopoly/finale/overlay/ScoreboardHUD.java#L45
> awoo: It iterates through every player and indiscriminately sets their scoreboard values.
> awoo: Like yeah, that's going to be slow.
> awoo: This is fairly straightforward to fix actually. Gotta track current values for all players and:
> 1. Only update the scoreboard when the values actually changed
> 2. Dynamically adjust the polling frequency based on the rate of change on a per-player basis
>    • Actually, probably best to listen to events instead of polling.
>    • Player's not wearing any armor at all? Don't run any code for that player until they trigger whatever event is responsible for > putting on armor.
>    • Only update armor dmg values on the "player took damage" event
>    • etc.
> ... but I have neither the time nor motivation to work on this 🤭
