### ISSUE TITLE
Knockback Modifiers have unexpected results

### ISSUE THREAD

**Issue by wingzero54** [CivMC/Finale#16]
As reported in #9 some kb modifiers appear to not work at all, and #15 at times the knockback is way stronger than it should be based on configuration. So between sometimes working, sometimes not, sometimes working too much, knockback is pretty unreliable and unexpected. Need to review the knockback modifier code and dive into whether it needs fixes to work properly, or should be removed to return vanilla-expected knockback.

**Comment by psygate** [comment]
https://github.com/CivMC/Finale/blob/be804cc270f7e07d622541c14248461ab189cfe2/paper/src/main/java/com/github/maxopoly/finale/combat/CombatUtil.java

Good luck. The method is 200 lines of nonsensical non-commented math related code, that has 20 if branches with 0 refactoring. Whoever picks this up, god speed brave soul.

**Comment by Aleksey-Terzi** [comment]
All the issues have been reviewed and fixed.

**Comment by Aleksey-Terzi** [comment]
> Good luck. The method is 200 lines of nonsensical non-commented math related code, that has 20 if branches with 0 refactoring. Whoever picks this up, god speed brave soul.

This because they use "copy-paste" from the original de-obfuscated code.
Though I agree, it would be nice to separate custom code from the MCs code because now is unclear if they put there custom code or it came from the old version of MC and now is changed.

**Comment by Diet-Cola** [comment]
Fixed by https://github.com/CivMC/Finale/commit/4f4e25ba5b879b2826b3dc2690a6e9fd6ad00506
