### ISSUE TITLE
Finale needs a config/change to poll armor less often.

### ISSUE THREAD

**Issue by psygate** [CivMC/Finale#17]
> I can't find where it was called but somewhere the time for how often it updates durabilities is hard coded to a specific number of ticks or something and it's too often https://github.com/CivMC/Finale/blob/master/paper/src/main/java/com/github/maxopoly/finale/overlay/ScoreboardHUD.java

Wingzero54 - 2022

**Comment by Diet-Cola** [comment]
The issue with this if I remember rightly is if we dont update it every x ticks, the scoreboard will disappear, surely there is a work around for this?

**Comment by psygate** [comment]
https://jd.papermc.io/paper/1.18/org/bukkit/scoreboard/Scoreboard.html

Official documentation says no limit except garbage collection apparently, and CivScoreBoard doesnt implement a timer or something. So... I guess we need to test this. Comment on the PR please. https://github.com/CivMC/Finale/pull/18


Edit: If this is true, we should offload the expensive calls to every X ticks, and update with precalculated values very Y ticks. The expensive part is probably polling the equipment & co, and network interactions. Let's try this simple solution and see how far we can go with this.

**Comment by psygate** [comment]
https://github.com/CivMC/Finale/pull/18

Related PR
