### ISSUE TITLE
Normal KB modifiers dont do anything, Sprint KB modifiers do

### ISSUE THREAD

**Issue by Diet-Cola** [CivMC/Finale#9]

**Comment by Diet-Cola** [comment]
Need verification but havent had any complaints

**Comment by Aleksey-Terzi** [comment]
In my tests kb modifiers didn't work for both normal and sprint.
This PR should fix the issue: https://github.com/CivMC/Finale/pull/23

**Comment by Diet-Cola** [comment]
Fixed by https://github.com/CivMC/Finale/pull/23
